# Generated by Django 4.0 on 2023-08-18 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='keywords',
            field=models.TextField(max_length=255),
        ),
    ]
