# Generated by Django 4.2.1 on 2023-05-24 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_alter_userprofile_is_client_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_work', to='service.serviceprovider'),
        ),
    ]
