# Generated by Django 4.2.1 on 2023-07-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_testimonials_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
    ]
