# Generated by Django 4.2.1 on 2023-05-28 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_alter_offer_service_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
