# Generated by Django 4.0 on 2023-08-18 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_offer_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='service_area',
            field=models.ManyToManyField(to='service.ServiceArea'),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='service_type',
            field=models.ManyToManyField(to='service.ServiceType'),
        ),
    ]
