# Generated by Django 4.2.1 on 2023-05-28 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_serviceprovider_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
