# Generated by Django 4.2.1 on 2023-05-28 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_serviceprovider_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='location',
        ),
    ]
