# Generated by Django 4.2.1 on 2023-06-01 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_remove_serviceprovider_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='service_area',
            field=models.ManyToManyField(to='service.servicearea'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='service_type',
            field=models.ManyToManyField(to='service.servicetype'),
        ),
    ]
