# Generated by Django 4.2.1 on 2023-06-03 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0009_serviceprovider_service_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='company_logo',
            field=models.ImageField(null=True, upload_to='company_logos/'),
        ),
    ]
