# Generated by Django 4.2.1 on 2023-06-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0010_alter_serviceprovider_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='contact_details',
        ),
    ]
